apiVersion: v1
kind: Pod
metadata:
  labels:
    app: healthz-101
  name: healthz-101
spec:
  containers:
  - name: healthz-101
    image: nginx:alpine
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
